[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# (optional, helps local Netlify dev)
[dev]
  framework = "vite"
  command = "npm run dev"
  targetPort = 5173
