[build]
  command = "npm run build"
  publish = "dist"

# Ensure client-side routing works (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: tighten security headers (safe defaults)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
