[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback for client-side routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200