[build]
  # Vite project: build command and output folder
  command = "npm run build"
  publish = "dist"
  base = ""

[build.environment]
  VITE_APP_NAME = "GloWell"
  VITE_API_BASE = "/"

# SPA routes fix (React/Vite): send all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
