[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Client-side routing: send all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
