[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

# API first (must come BEFORE SPA fallback)
[[redirects]]
  from = "/api/plan"
  to = "/.netlify/functions/plan"
  status = 200

# SPA fallback for client-side routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
