[build]
# आपका असली ऐप इस subfolder में है:
base = "Documents/MishbyHealthOS"

# Vite build command
command = "npm run build"

# Build output फ़ोल्डर (base के अंदर माना जाएगा → Documents/MishbyHealthOS/dist)
publish = "dist"

# (Functions use नहीं कर रहे, इसलिए यह key नहीं रख रहे)
# functions = "netlify/functions"

[dev]
command = "npm run dev"
port = 5173
targetPort = 5173
framework = "vite"
